### ISSUE TITLE
Selecting a part of a symbol highlights the rest of the symbol.

### ISSUE THREAD

**Issue by effectfully** [fgeller/highlight-thing.el#22]
Here's how it looks when I select `thing` in `highlight-thing-case-sensitive-p`:

![Screenshot from 2022-04-04 16-30-49](https://user-images.githubusercontent.com/10480926/161566457-447a5e22-d1fd-45fa-a0e8-717f88af28d4.png)

I don't remember than happening before. I think it started to work this way either after I switched to using the dark mode (unlikely) or after I upgraded to a newer emacs version (most likely).

Config:

```elisp
(use-package highlight-thing
  :ensure t
  :diminish)
(global-highlight-thing-mode)
(setq highlight-thing-case-sensitive-p t)
(setq highlight-thing-delay-seconds 0)
(setq highlight-thing-exclude-thing-under-point t)
```

Emacs version: 26.3.

**Comment by fgeller** [comment]
hi @effectfully! sorry for the delay! 
did you figure this out already? if not, could you provide a bit more context? ie what do you expect to happen instead? are the colors off?

**Comment by effectfully** [comment]
Hi @fgeller 

> did you figure this out already?

Sort of. I tried `idle-highlight-mode` and it didn't have the problem, so I switched to it. I also like how `idle-highlight-mode` doesn't highlight a word when the point is right after it.

> ie what do you expect to happen instead?

So when I select `thing` in `highlight-thing-case-sensitive-p`, the same `highlight-thing-case-sensitive-p` is fully highlighted for some reason despite `(setq highlight-thing-exclude-thing-under-point t)`. I think that only started to happen after an update and me switching to dark mode.

>  are the colors off?

Yeah, but that was an issue with my setup, ignore it.

**Comment by fgeller** [comment]
so if i understand you correctly all of `highlight-thing-case-sensitive-p` is highlighted rather than only `thing` which is the active region -- correct?

you can change this behavior multiple ways. for example: 
```emacs-lisp
(setq highlight-thing-what-thing 'region)
```
which will only highlight instances of the active region, `thing` in your example. 
or:
```emacs-lisp
(setq highlight-thing-prefer-active-region t)
```
which will switch to highlight the active region once the active region is active, otherwise it will highlight whatever thing you've configured via `highlight-thing-what-thing` (symbol by default). this is a hybrid approach and my default. 

as to not highlighting a word when point is right after it, that sounds like you're using evil-mode or similar :) let me know if you're interested and create an issue for it, shouldn't be too tough to add a config option for it.

closing this optimistically - please re-open if i misunderstood or you have further questions :)
