### ISSUE TITLE
Emacs freezes when highlighting an empty region

### ISSUE THREAD

**Issue by xsaga** [fgeller/highlight-thing.el#24]
Hi! Thanks for the package, but I think I found a bug that freezes Emacs (tested on Emacs 28.1 Windows 11).

When setting the highlight mode to region:

```emacs-lisp
(setq highlight-thing-what-thing 'region)
```
If i set the mark with C-SPC and then wait for `highlight-thing-delay-seconds` seconds (by default 0.5s), the CPU spikes to 100%, memory usage keeps growing and Emacs becomes unresponsive (can't use C-g or ESC, only way to exit is killing the process).

I think this happens when  `(point)` and `(mark)` are equal, the `highlight-thing-get-active-region` function returns the empty string and this is passed to the `highlight-thing-get-thing-at-point` function. I fixed this bug by replacing `thing` with `(if (string= "" thing) nil thing)` at the last expression of the `highlight-thing-get-thing-at-point` function:

```emacs-lisp
(defun highlight-thing-get-thing-at-point ()
  (let ((thing (if (highlight-thing-should-highlight-region-p) (highlight-thing-get-active-region)
                 (thing-at-point highlight-thing-what-thing))))
    (unless (member thing highlight-thing-ignore-list)
     (if (string= "" thing) nil thing)))) ;; <---
```

But I'm not sure if this is the proper place to fix this issue.

Thanks.

**Comment by fgeller** [comment]
hey @xsaga thanks a lot for reporting! took me a moment to figure out where things freeze, but turns out it's the call to `highlight-regexp` for me. added a guard in two places, hope that fixes the issue for you! let me know if it doesn't and either way, feel free to re-open the issue if you think there's something else to discuss :) again, thanks for reporting!
